### ISSUE TITLE
Lightbulb v2 always opens the UI even if the shortcut is set to start the app minimised

### ISSUE THREAD

**Issue by NomDeMorte** [Tyrrrz/LightBulb#112]
Just a minor annoyance, but it means that I need to close the UI every time I start the app.

![image](https://user-images.githubusercontent.com/45681208/68216172-9a955a00-0034-11ea-8105-396150c829cf.png)

Perhaps there is a command-line argument to start the app minimised to the systray, but I tried running lightbulb with /? and --help arguments and it just started as normal.

I am sorry about lots of issues filed lately, I am trying to be helpful with the new version (which I love!) I hope it isn't annoying.

**Comment by Tyrrrz** [comment]
This is by design, when you launch it directly you will see the main window as soon as it opens. It's not a great UX, in my opinion, when you launch something and then have to go look for it in the tray. :)

That said, it will not show the main window if it's launched automatically, i.e. on startup. Command line argument `--autostart` is responsible for that. If you want, you can add it to your shortcut.

**Comment by NomDeMorte** [comment]
That makes sense. 

Since I don't always want it running (I do some graphics analysis which I need to ensure is not interfered with) I tend to start it manually, and I have the autostart disabled (enabled in the app, but disabled via task manager's startup tab).

Still, I have added the argument to the shortcut and it now starts minimised to the tray, and the autostart remains disabled as above, so this is a good solution. Thanks!

I think it's OK to close this issue now. I felt like maybe I should have checked the source code for supported arguments, now I just feel lazy! :/ At least this issue will be here in case others have a strange use-case like mine.

**Comment by Tyrrrz** [comment]
Don't worry, every issue is worthwhile :)
