### ISSUE TITLE
.NET Core Runtime - hurdle for the user

### ISSUE THREAD

**Issue by jantheodor** [Tyrrrz/LightBulb#122]
I think the hurdance to use you app has become quite huge, and this is one thing I'd like to point out:

The user is "forced" to install .NET Core Runtime. Which I have to admit, as an hardcore pc user and windows enthusiast, never crossed my way, and I've been using Windows since 3.1. So my guess would be, that most "customers" won't recognize nor know of this tool and therefore distrust it (at least a tiny bit, because humans don't trust stuff that is totally new or unknown to them), even so it comes from Windows. Plus, you do not tell your users, which installers to choose (x68, x64) so they have to figure that one out for themselves too and since you don't offer an "please-install-everything-inside-before-you-launch-the-app"-bundle, you risk losing plenty of users at this early stage of the process already. Most users won't find their way to your github page nor will they read the "important note, that they have to install it" and thus end up with a non launching .exe file. It sure would be helpful if the .exe would create a popup if it failed to find .NET Core Runtime with further instructions written, to let the user know what to do next, and why it is, that the app won't launch at all.

**Comment by Tyrrrz** [comment]
Yes, you are completely correct.
The original plan for v2 was to bundle the runtime with installer but for various issues it didn't hit the deadline.
There are many ways this whole UX can be improved, but for the biggest part it rests on Microsoft's shoulders to provide better tools for developers to redistribute the runtime.
That said, .NET Core 3 is still quite new (it was released September 23) and I hope we will see improvements in this area as more and more apps will migrate.

**Comment by Tyrrrz** [comment]
For now I've added [this guide](https://github.com/Tyrrrz/LightBulb/wiki/How-to-install-.NET-Core-3-runtime) to wiki that includes all necessary steps to install .NET Core runtime.

**Comment by Tyrrrz** [comment]
With .NET Core 3.1 this is somewhat better now. The application will show an error if the runtime is not installed and offer you to download it. On top of that, it's now 1 installer instead of 2.

LightBulb is still currently on 3.0 but I've moved all existing links to point towards 3.1 because of the better installation process.

**Comment by jantheodor** [comment]
Dude that's awesome man. Thanks for the great work!

**Comment by xcasxcursex** [comment]
> With .NET Core 3.1 this is somewhat better now. The application will show an error if the runtime is not installed and offer you to download it.

I got this message and clicked yes to download it but nothing happened. I don't have Edge on this PC, so perhaps it's hardcoded to download it with that. 

Lightbulb worked when I installed the runtimes manually.

Also, the icon is back to normal now :)

**Comment by Tyrrrz** [comment]
It should definitely open the download link regardless of your browser. I haven't tested it myself, just learned about it yesterday.

**Comment by xcasxcursex** [comment]
No such luck I'm afraid. I imagine it's something I've done to my PC, and unique to me, but it might be worth testing. The good news is that the dotnet runtimes do now appear in the application uninstall list so the runtime can be removed to test it.

If it helps at all, The only error I seem to get is this event log:
![image](https://user-images.githubusercontent.com/58130821/70345664-a896fe80-18b0-11ea-86c2-43eb8138fa6a.png)

I tried starting lightbulb as admin, starting from a command line, etc, to try to get some more information.... Didn't work, sorry :(

**Comment by Tyrrrz** [comment]
Hm, I see, thanks for reporting. Just to clarify, the error dialog did appear it's just that clicking "yes" didn't do anything, right? Any chance you can take a screenshot of the error dialog please?

**Comment by xcasxcursex** [comment]
That's correct. Here's a screenshot of the message: 
![image](https://user-images.githubusercontent.com/58130821/70368123-47e0e380-18fb-11ea-945e-357a5f84a618.png)

**Comment by xcasxcursex** [comment]
Aha I found the problem - the 3.0 server runtime was already installed. When I uninstalled that, the 'yes' button in the above screenshot opened the link as expected. I had tried uninstalling the runtimes for 3.0 already, but the list was sorted in a strange way and the server runtime appeared separate to the others.

I still have the installers here so I can get it back to the failure mode, would you like me to do that so I can take screenshots?

**Comment by Tyrrrz** [comment]
It's fine, I got what I needed, thanks!

**Comment by John0King** [comment]
I'm just notice this from  stackshare,   and I'm  wondering why not use self containd  publish?  and  of course it will became 2 app (x86, x64)

**Comment by Tyrrrz** [comment]
@John0King ultimately self contained is not efficient in terms of space, especially as the windows app ecosystem is going to migrate towards .NET Core. If you pack LightBulb as a self-contained app you get (like you said) 2 sets of binaries, each over 100 mb in size (compare that to 8.2mb base size of the app). That's not favorable when it comes to autoupdate scenarios or just people downloading the app when they already have .NET Core installed. Of course you can "solve" this by providing more download options but that in turn has a cost as well.

Ultimately, I think self-contained distros (in the context of desktop windows apps) is not the solution to this problem, more of a temporary hack until Microsoft figures out how to streamline the runtime distribution story. There are many ways this can be improved, it was suggest to them and they're working on it. I've also shared some of the feedback with them that I gathered here and on other projects.

**Comment by John0King** [comment]
@Tyrrrz I'm kind of disagree, the Self-Contained app is only  94.6MB instead of 156MB if you use `<PublishTrimmed>true</PublishTrimmed>`,  and if this app update in a 3 years ,  the app will be around 100MB, but if it depend on  runtime framework,  the end user will install at least  600MB runtimes( 3 (runtime) * 2 (x86+x64) * 100MB ) ,  and the .net core runtime will not like the .net framework to replac with newer version, it'll install side by side !
and if user install other .net core apps, the user can not uninstall all of them , and note dotnet runtime can only be install on SystemDrive(C:\Program Files\dotnet\)

**Comment by Gitoffthelawn** [comment]
What is the **_total_** RAM consumption when using LightBulb:
1. If it is self-contained?
2. If it relies on external .NET Core runtimes?

Does installing .NET Core runtimes have any impact on RAM usage when no .NET Core apps are installed?

(BTW, I'm currently not using LightBulb mostly because of the .NET Core runtime installation requirement.  But it looks like a great application!)

**Comment by Tyrrrz** [comment]
RAM usage is largely dependent on the OS, bitness, phase of the moon, but it shouldn't be affected by whether .NET Core is installed machine-wide or comes with the application.

**Comment by Gitoffthelawn** [comment]
Thanks.  In that case, I vote that the application be self-contained and be fully portable (no writes to the registry, or any files outside of its own folder).

**Comment by mirh** [comment]
The dotnet maintainer are pretty lazy, so you should add an extra check for [W7 prerequisites](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=netcore31#additional-deps) in the install script.

**Comment by d4k0** [comment]
@Tyrrrz 
This may be a bit off-topic: Out of curiosity I tried .NET Desktop Runtime 5.0.1 with LightBulb today, but it doesn't start. No error message is shown. I'm much more into Java, but wasn't .NET 5.0 supposed to consolidate .NET Framework 4.8 and .Net Core 3?

**Comment by Tyrrrz** [comment]
@d4k0 the app is still using .NET Core 3.x, so .NET 5.0 runtime is currently incompatible. The links in the readme should point you to a direct download of the correct version. I'm looking into ways to enable an upgrade path, but currently a lot of users don't have .NET 5.0 installed and the next application autoupdate (that would use .NET 5.0) would render the app unusable for them. Will probably have to create a native bootstrapper to install the runtime automatically, because MS seems to be incapable of doing it themselves.

**Comment by Tyrrrz** [comment]
.NET Runtime is now installed automatically when starting the application (latest master).
