### ISSUE TITLE
[Feature request] No-install / portable version

### ISSUE THREAD

**Issue by vatterspun** [Tyrrrz/LightBulb#13]
**Current behavior**

Program is installed and saves settings to _AppData\Roaming\Configuration.dat_

**Requested behavior**

A ZIP or self-extracting archive that will run in place and save settings locally.

**Use cases**

* Users whose machines have installation disabled by the admin.  With a portable version, you just copy over items from a flash drive and run.
* Users who want to have LightBulb setup the same across multiple machines could run the program over a cloud or network drive to sync the same color temp setup.
* Ease of backup 

**Possible issues**

Notably this can make updating the client more complicated as you have to know to update some files and not others, so it is recommended as an optional setting or a separate version.

**Comment by Tyrrrz** [comment]
%appdata% folder is the recommended preferred folder for user configuration. https://blogs.msdn.microsoft.com/patricka/2010/03/18/where-should-i-store-my-data-and-configuration-files-if-i-target-multiple-os-versions/

> Users whose machines have installation disabled by the admin. With a portable version, you just copy over items from a flash drive and run.

Then the program will not work anyway because it needs to write to HKLM registry (admin privs) and also create a startup shortcut (maybe admin privs).

> Users who want to have LightBulb setup the same across multiple machines could run the program over a cloud or network drive to sync the same color temp setup.

LightBulb also saves settings when it closes, imagine the possible number of conflicts when doing so. :frowning:

> Ease of backup

I don't see the advantage here. It would make sense if you were backing up both the binaries and the config file, but why would you do that.

**Comment by vatterspun** [comment]
> %appdata% folder is the recommended preferred folder for user configuration.

There are not a small number of programs that have this feature, but it sounds like you have strong feelings on this point so I'll leave it.

**Comment by Tyrrrz** [comment]
I feel like this feature will not be useful for too many people. Implementing it isn't difficult, but maintaining and testing it is. I can't really imagine people carrying LightBulb on their stick drives, launching it manually and so on.

Among the points you explained, only the second one makes sense to me, but having no installation privileges still doesn't prevent the program from writing to %appdata%, so you can still use it normally.

**Comment by vatterspun** [comment]
It's true that programs like (for example) LibreOffice have any of 1,000 different modifications that would be very difficult to do on every machine you touch.  Meanwhile, LightBlub doesn't have that many settings to modify so setting it up on another computer wouldn't be too difficult.

You're also right that there's not a broad user base for this feature.  Still, a version that doesn't require admin / installation would probably see a few more downloads overall.

**Comment by Tyrrrz** [comment]
Along the installer, I'm also attaching a zip archive with just the binaries, since the last release

**Comment by vatterspun** [comment]
> Along the installer, I'm also attaching a zip archive with just the binaries, since the last release

Very cool, thanks.

**Comment by smaragdus** [comment]
SunsetScreen (http://www.skytopia.com/software/sunsetscreen/) has a portable version.
A switch- for example "LightBulb.exe -portable" or "LightBulb.exe --portable" forcing the program to save data and settings in program folder and load them from there might be a possible solution.

**Comment by Tyrrrz** [comment]
Recent changes to my settings library made implementing this feature trivial so there you go 😋

**Comment by smaragdus** [comment]
I prefer portable programs not because I use them on other machines so often but because they are very easy to back-up. For example I have all my portable program (thousands) in a separate folder and when I have to re-install Windows I just back-up this folder to an external drive and after re-installation I just copy this folder back and I have all my portable programs with all their settings and data- this usage spares me saving registry keys and exploring AppData to decide what to save and what to skip (with time AppData becomes a junkyard) and installing lot of stuff. So for me a portable version of LightBulb would be a convenience. I agree that programs like ClassicShell for example, which integrate with system on a very low level cannot be portable. I also agree that most users won't benefit much from a portable version- I suppose most of then do not even know what "portable" really means.
Thank you for your immediate response!

**Comment by smaragdus** [comment]
@Tyrrrz
Many thanks for the portable option, much appreciated.
I have already notified The Portable Freeware community about it:
https://www.portablefreeware.com/forums/viewtopic.php?p=85588#p85588

**Comment by Tyrrrz** [comment]
@smaragdus Thank you. The .NET framework version used is 4.5.2

**Comment by smaragdus** [comment]
**@Tyrrrz**
I edited my post quoting the information about .NET version you provided, thank you.

**Comment by smaragdus** [comment]
**@Tyrrrz**
LightBulb was given its own thread at The Portable Freeware Forum:
https://www.portablefreeware.com/forums/viewtopic.php?f=4&t=23321

**Comment by vatterspun** [comment]
I've been using this version for ~2 weeks now and it's great.  Thanks so much.
