### ISSUE TITLE
Plugging/unplugging USB devices resets luminosity & temperature

### ISSUE THREAD

**Issue by qlassiqa** [Tyrrrz/LightBulb#147]
I've been using this app for a while and this bug started to really annoy me - basically in Night mode every time I plug in or unplug something via USB, both the luminosity & temperature are reset to Day mode but the app still shows that it's in Night mode, so I have to toggle the app Off and On to put it back in Night mode.

- Windows 10 1809 with up-to-date Nvidia GPU drivers

**Comment by xcasxcursex** [comment]
Sounds annoying :( I'm not seeing this behaviour.... I don't think this is a Lightbulb bug. You might need to do some work to find out what's so special about your PC.

Do you have gamma polling enabled in Lightbulb's settings? If not, does enabling that correct the issue in a short time without interaction by you?


First off I'd check the Windows Event Viewer to see if there are any messages there which might indicate that something has changed which should not have.

If not, since it's a mystery, a 'process of elimination' is the most effective approach - basically this means, 'try something and go, "nope that wasn't it, I'll try the next thing", until it breaks'. It can be time consuming, but it works.


I wonder if one of your USB devices is doing something strange.... 

It has occurred to me, the 20x0 series nvidia cards have a USB C connector for monitors, perhaps that has something to do with it? Which Nvidia card do you have? Are you using a USB monitor?

Have you installed the latest firmware and drivers from your manufacturer's website, for your motherboard? Do you have any additional USB ports installed (PCIe cards or something)? No modded USB drivers or anything like that?

Do you do any 'tweaks' to Windows? There are a _lot_ of bad ones out there, there might be one that's causing this. 

Perhaps it's also some other software you have installed. If you close all other running software in the background, does this issue still occur?


To start with a process of elimination, I would try this:

At night, so lightbulb will be in night mode, disconnect all your USB devices except your keyboard (connected directly to the motherboard, not a hub), and reboot. Don't shut down and start up, wince Win10 doesn't actually shut down by default, it just hibernates ("Fast boot") - specifically select 'restart' from the menu. Since you have the keyboard connected, you will be able to log in and control the machine. Now disconnect and reconnect the keyboard. Does it still reset the display?

If it's fine like that, then start connecting, then disconnecting, then re-connecting, other USB devices, repeat this one device at a time, until it breaks. That'll tell you if it's some USB device messing with it, and which one it is.

If even just the keyboard does it, then at least you have narrowed it down to the keyboard, its driver/software, or some other issue. 

Sounds kinda tedious, I know, but it will tell you a lot and only cost a few minutes of your time.

Before I suggest it..... @Tyrrrz  Would Lighbulb even work in 'Safe mode'?

**Comment by qlassiqa** [comment]
Thank you for the detailed advice @xcasxcursex, but the elimination process is too tedious for my computer and involves too much effort for something that should not happen no matter what configuration I have.

Long story short, I uninstalled it and instead I'm now using the F.Lux app, which works out of the box without any such problems whatsoever.

**Comment by xcasxcursex** [comment]
Too much effort? Come on it's literally 5 minutes. 
"something that should not happen no matter what configuration I have " That is not how computers work ;) And as it turns out,  your choice of operating system is exactly the problem, so it is your configuration.

Anyway as you were smart enough to check and see if anyone else had this problem:
Well the only other example I can find is this one: https://github.com/Tyrrrz/LightBulb/issues/77

And the resolution is to enable gamma polling, as I suggested.

That issue also links to the f.lux forum which explains that this is a bug in Windows. So it is your computer. It's just that because of the way f.lux works out of the box, it constantly updates (at the expense of performance), so you still have the problem, you're just not seeing it.

Since I'm on 1909 and not seeing this issue, maybe it might be a good time to update, since apparently Microsoft have fixed this. Your OS is a year and a half old :O
Then again, 2004 is due out any week now, so maybe wait a little while and fix your PC with a fresh install.

**Comment by Tyrrrz** [comment]
Closing now as gamma polling has been introduced.
