### ISSUE TITLE
Multiple monitor support

### ISSUE THREAD

**Issue by xTheEc0** [Tyrrrz/LightBulb#15]
Hey, this is almost going to look like a post, on whats wrong and could be improved.

So I have been using LightBulb for a few days and noticed that 'Pause if fullcsreen' checks current window only. 
So for example, if I play LoL on Borderless, it will work great, as soon as I tab out (lets say to a chat for a few secs) it starts transitioning back to night mode. Tab back into game, and it transitions back. 
Slightly annoying.

Another king I have with this is that it affects the whole desktop. (I am not sure if this would be possible to fix but...)
It would be great if it only affected the monitor that has the fullscreen app running. 
So for example, one monitor runs a game, and is in day mode, secondary monitor is in night mode.

Otherwise great app, loving it : )

Thank you, 
xTheEc0

**Comment by Tyrrrz** [comment]
Hi. Thanks for using LightBulb.

> So I have been using LightBulb for a few days and noticed that 'Pause if fullcsreen' checks current window only.
> So for example, if I play LoL on Borderless, it will work great, as soon as I tab out (lets say to a chat for a few secs) it starts transitioning back to night mode. Tab back into game, and it transitions back.
> Slightly annoying.

Yeah that's the intended behavior. You want it to stay disabled while LoL is launched even if it's not in foreground?

> Another king I have with this is that it affects the whole desktop. (I am not sure if this would be possible to fix but...)
> It would be great if it only affected the monitor that has the fullscreen app running.
> So for example, one monitor runs a game, and is in day mode, secondary monitor is in night mode.

It's been requested before. I'm not 100% sure but I think this CAN be done theoretically. The problem is that it implies reworking a huge portion of the code, introduces a lot of complications as a result, and all that for only one rather small function - "pause when fullscreen", which not a lot of people use. That's why I've been hesitant to implement it. Maybe in the future I will change my mind, who knows.

I extracted your 2nd suggestion to a [separate issue](https://github.com/Tyrrrz/LightBulb/issues/16) since your post is a bit too broad.
