### ISSUE TITLE
Manual proxy settings not used

### ISSUE THREAD

**Issue by monoludic** [Tyrrrz/LightBulb#18]
Hi,
I tested the manual proxy settings. It does not work currently. 

The test [here](https://github.com/Tyrrrz/LightBulb/blob/9768e68c0b3903e4c282db4b0f085f1f44f3abae/LightBulb/Services/FileSettingsService.cs#L234) is never true (even with `args.PropertyName` containing "Proxy"). Therefore `UpdateConfiguration` is never called and the proxy is not set. There may be a bug or a misuse of the extension method `IsEither`.

By the way you should modify the host example you provided in the [Proxy wiki page](https://github.com/Tyrrrz/LightBulb/wiki/Proxy). The host should not have the `http://` prefix: ~~http://~~ proxy.server.com
(https://msdn.microsoft.com/fr-fr/library/xfsh37cx(v=vs.110).aspx#Notes)

**Comment by Tyrrrz** [comment]
Hi.
Damn, I suspect the compiler chooses the wrong IsEither overload.
Changed the wiki, thanks.

**Comment by Tyrrrz** [comment]
Normally `IsEither` should check equality for all items listed in parameters. For whatever reason, I used to have multiple properties passed as argument to that `IsEither` but then I removed all but one, leaving just the `nameof(Proxy)`. Instead of treating `nameof(Proxy)` as an actual object, it resorted to an overload that takes `IEnumerable` as parameter, treating it as an array of characters. Oops.
