### ISSUE TITLE
Reset to day-time state at midnight

### ISSUE THREAD

**Issue by Snaxeko** [Tyrrrz/LightBulb#180]
At midnight (00:00) if the sunset time is lower than 00:00 it always reset to day-time state (instantly goes to 6500K 100% brightness like it should be the day), then at the end of transition duration, it instantly goes to the night-time mode.

### Steps:
1) Set the sunset time to 23:35 (any before 23:59) & sunrise to 07:20
_Temperature decreases slowly as intended._
2) At 00:00, going back to 6500K (day-time setting) in 3-4 secs 
3) At (night-time hour + transition duration time) it will switch to the night mode in 3-4 secs

**Step 3 detail:**
1) Set the sunset time to 23:00
2) Set transition duration time to 1:15
3) Wait until it's 00:15.

At 00:15 it will switch from day mode to night mode in 3-4 secs.

Using LightBulb v2.2.0 on Windows 10

**Comment by e-t-l** [comment]
Confirming this bug occurs as described as of v2.3.3

**Comment by Tyrrrz** [comment]
@e-t-l What's your sunrise/susnet?

**Comment by e-t-l** [comment]
@Tyrrrz 
Sunset: 8:25 pm, sunrise: 5:45 am. Set automatically via location.

**Comment by Tyrrrz** [comment]
I have sunrise at 4:45 am and sunset at 9:11 pm, but can't reproduce this issue

**Comment by e-t-l** [comment]
I was working late tonight and saw this happen again as the clock hit midnight, so here's all the information I tell right now (P.S. There's no error log feature, is there? That would be super helpful in these situations :/ )

- A couple seconds after midnight, Lightbulb quickly transitioned to full daytime temperature. 
- If I switch to _manual_ solar configuration, it quickly transitions back to the correct nighttime temp. (This is only a temporary workaround though, because I really like the location-based feature).
- Current location-based sunset time is 8:27 pm. It's 12:05 am right now. 
- Transition duration is set to 4 hours, transition offset set to 10%. So transition should end around 12:03.
- Like Snexako originally described, once the transition end time is reached, color temperature goes to correct nighttime values over the course of several seconds. 

@Tyrrrz When you tested this, did you confirm that at midnight, the transition is not 100% complete? Just in case you haven't, could you let us know what happens when you follow the exact steps Snexako described?

> 1. Set the sunset time to 23:00
> 2. Set transition duration time to 1:15
> 3. Wait until it's 00:15.

I'd expect that you'd see your transition go from 80% complete at midnight back to full daytime temperature, then 15 minutes later, it would revert to the correct 100% nightttime temp.

**Comment by Tyrrrz** [comment]
Finally tracked this one down :)

**Comment by Tyrrrz** [comment]
Should be fixed now. You can try the downloads in the latest CI build: https://github.com/Tyrrrz/LightBulb/actions/runs/1191432271
