### ISSUE TITLE
Does LightBulb address subpixel flickering, like IRIS?

### ISSUE THREAD

**Issue by jantheodor** [Tyrrrz/LightBulb#181]
Hey Alexey. Just wanted to ask if LightBulb does adress the subpixel flicker "issue" that "IRIS" does advertise so heavenly on (https://iristech.co/pwm-flicker/)? Thanks for the response.

**Comment by Tyrrrz** [comment]
Hi.
I've skimmed through the article and, if I understand correctly, this is the main point, right?

![image](https://user-images.githubusercontent.com/1935960/99536880-9b84f980-29b3-11eb-826e-a695fd2ff55a.png)

If so then yes, LightBulb also changes temperature/brightness on a software level by modulating the gamma, rather than changing the brightness of the monitor. Actually, doing it this way is much easier from the programmatic perspective too.

I'm not entirely sure what "removing the white point" means as I'm not very well-versed in this terminology, but I assume they're talking about reducing the intensity of colors, which is essentially what the brightness setting does.
