### ISSUE TITLE
[question] is your political ToU agreement a requirement?

### ISSUE THREAD

**Issue by atesin** [Tyrrrz/LightBulb#254]
### Version

any

### Details

i am not agree with what you say in your tems of use... basically you say whoever use this software must believe russians are evil, and i dont think so... i think that trying politicize software goes far beyond against spirit of free software, because you are imposing restrictions, as richard stallman also had said

i am not saying russians are angels, but certainly things are not so binary actually... according the information from both sides i SEARCHED and ANALYZED MYSELF (besides which flooded by cnn, fox, bbc, reuters and other mass western media), russians felt forced to "invade" ukranie ("invasion" itself is a term generated by western media) because according their intelligence, they discovered NATO (which ukranie is not part of) were amassing weapons to be launched against russia NEXT DAY, so they had no choice... but nobody knows because nobody talks about it because are taboo

i am also not against ukanian people...  wars are catastrophic for whoever people of whahever side... powerful people play their games according their caprices while people suffer the consecuences, without they even considering us

that said... until i am really interested in this software, i won't download as i don't think russians are evil, but instead i believe unfortunately ukranians are more victims of your own current corrupt government and his allies....  for same reason, i DO however SUPPORT UKRANIAN **PEOPLE**

### Steps to reproduce

- read lightbulb ToU
- believe russians are not as bad as they had no other choice to stop his own invasion urgently
- download and install lightbulb anyway
- feel morally bad using it

**Comment by Tyrrrz** [comment]
> feel morally bad using it

Good.

https://github.com/Tyrrrz/.github/blob/master/docs/why-so-political.md

**Comment by comradekingu** [comment]
@atesin 
The wording of
>By using this project or its source code, for any purpose and in any shape or form, you grant your implicit agreement to all the following statements:

is indeed a requirement.

From the license

> c) You must license the entire work, as a whole, under this
    License to anyone who comes into possession of a copy.  This
    License will therefore apply, along with any applicable section 7
    additional terms, to the whole of the work, and all its parts,
    regardless of how they are packaged.

(From 7)
>Additional permissions that are applicable to the entire Program shall
be treated as though they were included in this License, to the extent
that they are valid under applicable law.  If additional permissions
apply only to part of the Program, that part may be used separately
under those permissions, but the entire Program remains governed by
this License without regard to the additional permissions.

  When you convey a copy of a covered work, you may at your option
remove any additional permissions from that copy, or from any part of
it.
…
 All other non-permissive additional terms are considered "further
restrictions" within the meaning of section 10.  If the Program as you
received it, or any part of it, contains a notice stating that it is
governed by this License along with a term that is a further
restriction, **you may remove that term**.

(From 10)

(A part about how the rights propagate)

**You may not impose any further restrictions on the exercise of the
rights granted or affirmed under this License**.  For example, you may
not impose a license fee, royalty, or other charge for exercise of
rights granted under this License, and you may not initiate litigation
(including a cross-claim or counterclaim in a lawsuit) alleging that
any patent claim is infringed by making, using, selling, offering for
sale, or importing the Program or any portion of it.

@Tyrrrz If part of the appeal is keeping your livelihood, keeping with the license is a good idea.
GitHub can't allow themselves to be a platform for breaking the GPLv3.
You can trash anyone as much as you want before you get to what GitHub dictates.
The problem is requiring of others to do the same.

**Comment by donotsdubba** [comment]
The author is so factually-ignorant and morally-deprived he tried to push one-sided brainwashed propaganda onto libre software via licensing, of all things. Utterly disgusting, void of humanity and thoroughly socially-irresponsible.

That being said, neither Russia, NATO, Ukraine, China, Israel, UAE etc. are anyone's allies, nor are they each others' enemies. Those that know, know. All you need to do is to carefully gather the data and actual verifiable facts about how they cooperate behind the scenes. Again, those that know, know. As the saying wisely goes, "don't cast pearls upon swine", so I will elaborate no further here.

Nonetheless, the OP's general _**sentiment**_ is 100% correct as a matter of demonstrable fact. (Although not as much so on the exact details.)

**Comment by MichaelAgarkov** [comment]
Politics in software EULAs should **NOT** be a thing.
