### ISSUE TITLE
Process whitelist

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/LightBulb#39]

**Comment by LakeishaKowalczyk** [comment]
Looking forward it

**Comment by Tyrrrz** [comment]
@NomDeMorte @Dainius if you have time, please test this out :)

**Comment by NomDeMorte** [comment]
Whitelist is working like a charm. Both with gamma smoothing on and off, across wide ranges, spamming backwards and forwards, can't get it to break.

There are a couple of potential issues that came up when testing:

Setting explorer.exe as a whitelisted item has issues. Alt+Tab, hovering taskbar, opening the start menu, etc, all cause the whitelist to disengage lightbulb. If a user wanted the file explorer to be whitelisted, this could be an issue. Thinking of AHK, I know there are many ways to select an open window, so perhaps you could make it use something like that, or just not include explorer in the list, or just, users can deal with Windows being stupid and using the same .exe for everything ;) I don't know, you're very clever, I'm sure you can think of the best way to handle it. I have no idea :)

Unrelated to the whitelist issue with the new build:

settings.dat is now settings.json. Obviously these are the same format and i was able to just copypaste the old config in there, but not sure if the new name is intentional, or how end-user migration might be handled.

**Comment by Tyrrrz** [comment]
>Setting explorer.exe as a whitelisted item has issues. Alt+Tab, hovering taskbar, opening the start menu, etc, all cause the whitelist to disengage lightbulb. If a user wanted the file explorer to be whitelisted, this could be an issue. Thinking of AHK, I know there are many ways to select an open window, so perhaps you could make it use something like that, or just not include explorer in the list, or just, users can deal with Windows being stupid and using the same .exe for everything ;) I don't know, you're very clever, I'm sure you can think of the best way to handle it. I have no idea :)

Good point. It shouldn't show up on the list.

>settings.dat is now settings.json. Obviously these are the same format and i was able to just copypaste the old config in there, but not sure if the new name is intentional, or how end-user migration might be handled.

Yeah the name change is intentional. I'm only concerned with backwards compatibility between releases and 1.6.4.1 settings will not be compatible either way.

**Comment by NomDeMorte** [comment]
> It shouldn't show up on the list.

INB4 someone complains that they can't whitelist the file explorer. Then you make it appear in the list and people will  complain that alt-tab breaks lightbulb. Then you make a UI with a window picker and people will complain about the complex UI and ask for a simple UI like a checklist.

There's no winning the Windows game, sometimes ;)

**Comment by Tyrrrz** [comment]
I hope that won't happen :D
