### ISSUE TITLE
Support for ICC profiles

### ISSUE THREAD

**Issue by Metaception** [Tyrrrz/LightBulb#44]
A ICC profile stores gamma values for use by a display calibration software. Both the built in Color Management in Windows and F.lux support this format.

I am using [QuickGamma](https://quickgamma.de/indexen.html) to fine tune the gamma values (and it gives you easily reproducible values), though there are dedicated [sites](http://www.tftcentral.co.uk/articles/icc_profiles.htm) to share ICC profiles.

I tested LightBulb's portable version and it resets the gamma values to 2.2 ( Windows default). I hope LightBulb can add support for these profiles.
Well either way, nice app!

**Comment by Tyrrrz** [comment]
Hi @Metaception 
Sorry for the late reply. I'm trying to cleanup and groom issues.
Can you please elaborate on the full story behind this issue? How will you use this functionality and how do you see it being accessible in the app? I'm not familiar with ICC profiles at all so I'm not sure what benefit this provides.

**Comment by Metaception** [comment]
I stopped using Windows so I am no longer using LightBulb.

ICC profile is for calibrating displays, with ICC support the gamma changes would respect the screen calibration instead of resetting it

**Comment by PeterSHollander** [comment]
I also work closely with ICC color profiles.  A major benefit of LightBulb utilizing the gamma values set in the active ICC profile would be that color rendering of software during daytime (presumably 6500K) would match the sRGB D65 standard (monitors having a 6500K white point).  Essentially, if LightBulb is just assuming that a 2.2 gamma is fine for all color channels, but in reality some gamma values are 2.0 or lower, then when it's reporting 6500K it could be off by a couple 1000K.  I'll admit I have not yet played around with LightBulb, so there's a chance this feature has already been patched; but I figured I'd join in the conversation since the issue isn't closed and I'd be able to clarify the importance of having (open source!) blue light filtering software that accommodates ICC color calibration.

**Comment by AnRetset** [comment]
ICC color profile support would be great.  My monitor has a white point of 9300K (the NTSC-J standard), rather than the sRGB standard of 6500K.  The gamma curving LightBulb enacts feels far too blue, even at the "lowest" setting of "1000K" (seemingly because my monitor's white point is 3000K above the sRGB standard?)  _To clarify, I am expecting that by 1000K, I should not be able to discern the difference between blue and black, ie. all blue should be eliminated at the lowest color temperature setting._  Please clarify if this is not the intended behavior of the application.

This problem seemingly could be solved by having LightBulb read the currently active ICC color profile, and then offset the gamma using that ICC profile as a base point (rather than assuming that a 2.2 gamma is correct for all color channels).  Redshift achieves this using the -p command (for "preserve" color profile).

Alternatively, if ICC color profile support seems difficult for whatever reason, at least adding in a "default gamma offset" option would be very much appreciated for us to manually input our color profile calibration settings.

**Comment by Tyrrrz** [comment]
Thank you for clarifying the use case. That sounds like an important feature. I will have to figure out what's the best way to adapt the behavior. I'm guessing I could get the display gamma prior to launching LightBulb and use that as base point. However, then it won't work if the user changes gamma while LightBulb is running. Additionally, gamma set on the monitor directly may not be accessible from software, I'm not sure. I guess a setting to configure the basepoint is the easiest solution, although not the most user friendly.

**Comment by AnRetset** [comment]
For the users that care this much about colour accuracy, I don't think we'd mind having to input the values once manually, even if it is in a config.json file or something ;)

**Comment by dave7280** [comment]
> Thank you for clarifying the use case. That sounds like an important feature. I will have to figure out what's the best way to adapt the behavior. I'm guessing I could get the display gamma prior to launching LightBulb and use that as base point. However, then it won't work if the user changes gamma while LightBulb is running. Additionally, gamma set on the monitor directly may not be accessible from software, I'm not sure. I guess a setting to configure the basepoint is the easiest solution, although not the most user friendly.

This is very important feature as there are plenty of frustrated FLUX users who are having problems with this.

eg. I use ICC profile to fix colors of my display to calibrated ones.

The application should load the default ICC profile at start and restore it at the exit. 
This is all what it has to do.

Current behaviour is that it disables all ICC profiles on start and of course doesnt restore the profile at the exit.

**Comment by Tyrrrz** [comment]
Hi.
Unfortunately I have to descope this issue as the project has moved into maintenance mode, which means that new features are unlikely to get implemented.

**Comment by PeterSHollander** [comment]
Understandable, thanks so much for the work you have done on this project!

**Comment by Tyrrrz** [comment]
Thank you @PeterSHollander ❤️
