### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by Yvan-Masson** [Tyrrrz/LightBulb#45]
Hi,

Thanks for this wonderful software. Would it be possible to add internationalization support to allow translation?

Regards,
Yvan

**Comment by Tyrrrz** [comment]
Hi @Yvan-Masson 
I have interest in this. Do you have any suggestions in regards to crowd-sourcing translations?

**Comment by Yvan-Masson** [comment]
Sorry @Tyrrrz, I don't know enough about internationalization to suggest a proper way to do this.

**Comment by fabiorfreitas** [comment]
I think [OneSky] is free for FOSS projects. [Launchpad] seems to be an even better solution.

Other tools that also look promising are [Zanata], [Pootle] and [Weblate].

If you ever start a translation project, please message me, I would be very much willing to help with Brazillian Portuguese :)

[OneSky]: https://www.oneskyapp.com
[Launchpad]: https://launchpad.net
[Zanata]: https://zanata.org
[Pootle]: https://pootle.translatehouse.org/index.html
[Weblate]: https://weblate.org

**Comment by xkonglong** [comment]
I can help translate xaml files

**Comment by xkonglong** [comment]
xaml  add uid。

ex：

<TextBlock
                                Margin="4,0,0,0"
                                VerticalAlignment="Center"
                                Text="ABOUT" Uid="{DynamicResource TextBlockUid1}" />

**Comment by xkonglong** [comment]
https://docs.microsoft.com/zh-cn/dotnet/desktop/wpf/advanced/globalization-for-wpf?view=netframeworkdesktop-4.8

**Comment by KovalevArtem** [comment]
> It is sad that the application is only in English - I propose to translate.
> I am ready to help in the translation into Russian.
> (For example, you can use **Weblate**, or any other service. It is completely free for open source projects.)


Tyrrrz:
> Yes, localization would be really nice. In the past I have already created an account for LightBulb on Crowdin, but it didn't get anywhere past that point. Currently there are still a few open questions:
> 
> * How should the localizable strings be stored? Is there a common/standard/popular format? I don't want to build a custom one if I could avoid it.
> * How should the localization process be synchronized with development? What happens if new strings are added and there is no one to translate them?
> * How should the localization be deployed? For example, releasing new features/bug fixes can't be delayed by waiting on localization, so it's likely they won't be deployed in tandem.

@comradekingu Need your help!

**Comment by comradekingu** [comment]
I can help set it up on https://hosted.weblate.org/hosting my account is https://hosted.weblate.org/user/kingu/

**Comment by Tyrrrz** [comment]
@comradekingu how will the localization strings get pulled into the app? What is the most common process for these?

**Comment by xkonglong** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/tools/winres-exe-windows-forms-resource-editor

To localize using Winres.exe, you must first develop an application using a visual designer like the Windows Forms Designer in Visual Studio. When development is complete, set the form's LocalizableAttribute (the Localizable property in the Properties editor) to true, and then hand off the .resx file for the default culture to a third-party localizer. This .resx file contains extra information that Winres.exe uses to recreate a design-time version of the original form.

**Comment by comradekingu** [comment]
@Tyrrrz What kind of format does it use?

As for the Weblate part
Set up libre account and project at https://hosted.weblate.org/hosting/
Point it to the POT and PO files in the setup process
Add webhooks and GitHub user https://docs.weblate.org/en/latest/admin/continuous.html?highlight=webhook#automatically-receiving-changes-from-github
Select whether you want [rebase or merge](https://docs.weblate.org/en/latest/admin/continuous.html?highlight=webhook#merge-or-rebase)

**Comment by roxfr** [comment]
In my point of view, Weblate (MATE Desktop, Ukui Desktop, LxQt, ...) or Transifex (Xfce, Deepin, ...) are the best solutions. You should not use Launchpad which is too locked (for example : Ubuntu, Elementary OS).
=> [Online Web Translator Comparison Table](https://docs.google.com/spreadsheets/d/1t6Zo9OmlRCH3N9dOumnWn0w8QrgI9Is2zQXSJB7K-QI/edit#gid=0)

**Comment by comradekingu** [comment]
@roxfr [elementaryOS also](https://medium.com/elementaryos/adios-transifex-weve-gone-to-weblate-59870dea06b2) uses [Weblate](https://l10n.elementary.io/)
Launchpad has gotten viable again, and Transifex still isn't. Weblate is IMO. the obvious choice when you factor in the terms and agreements and usability.

**Comment by Tyrrrz** [comment]
@comradekingu 

> As for the Weblate part
Set up libre account and project at https://hosted.weblate.org/hosting/
Point it to the POT and PO files in the setup process
Add webhooks and GitHub user https://docs.weblate.org/en/latest/admin/continuous.html?highlight=webhook#automatically-receiving-changes-from-github
Select whether you want rebase or merge

Thanks. I would probably prefer to merge translations manually, but it's a different concern.
The part, which is not clear to me is how to organize the deploy/deliver pipeline for translation files. I imagine that translations will not be 100% most of the time (i.e. because new strings are added, etc.), so there needs to be a way to release a new version of LightBulb with incomplete translation. At the same time, new translation releases may need to be made available separately from LightBulb releases. I'm just curious if there's an example of how this process was established in other small-scale open source projects.

**Comment by roxfr** [comment]
> @roxfr [elementaryOS also](https://medium.com/elementaryos/adios-transifex-weve-gone-to-weblate-59870dea06b2) uses [Weblate](https://l10n.elementary.io/) Where is UKUI translated?
> Launchpad has gotten viable again, and Transifex still isn't. Weblate is IMO. the obvious choice when you factor in the terms and agreements and usability.

Ok, I was wrong for Elementary OS (note : I still have a pending request for their dock).
I tried to complete the translation for "plank" and "docky" (extensions) on Launchpad.
In my part, I find it a bit heavy and not very user-friendly (need candidacy / after a while, if your translations are good, you will be invited to join the team).
Otherwise, I regularly translate Deepin OS into French on Transifex.
I have not had any particular problem (however, it is a paid solution).
I also used Weblate to translate LxQt and Ukui Desktop  - See : [ukui](https://github.com/ukui/ukui-sidebar/issues/352)
Yes, you have to find a user-friendly solution with the right terms and agreements (not easy to find).
Otherwise, there's the good old Poedit and queries in Github.
Regards,
Roxfr

**Comment by hotellinawebmaster** [comment]
Whenever you are ready I would be willing to help for Italian language.

**Comment by m2u-84** [comment]
Let me know, whenever this takes off. Will gladly provide German translation.

**Comment by Tyrrrz** [comment]
Unfortunately, I have to close this as I don't feel like I have the capacity to reconcile the added complexity of introducing this feature. Sorry.
