### ISSUE TITLE
Extend colour temperature range

### ISSUE THREAD

**Issue by ghost** [Tyrrrz/LightBulb#55]
AMD drivers go up to 10k for instance, my screen is very warm by default so I use 7000k to make it the equivalent of 6500k

Lightbulb limits this to 6600k so I have a yellowish tint during the day

**Comment by Tyrrrz** [comment]
Sorry for late reply.
I believe you can circumvent this limit by editing the config manually https://github.com/Tyrrrz/LightBulb/wiki/Config-file.

**Comment by axydavid** [comment]
Hi, awesome program, I just have 1 tiny small issues.
I have been searching for a propper open source implementations of flux, because some propietary ones used a significant amount of cpu, I'm guessing it might be a bitcoin miner.
With the other propietary programs I can go beyond 2500k, I can't with this one.
I have already tried the config tweak to no avail, any plans on  including more temperatures in the future?

**Comment by Tyrrrz** [comment]
There's no limit in config. What version are you using?

**Comment by Tyrrrz** [comment]
There's no limit in config. What version are you using?

**Comment by Tyrrrz** [comment]
There's no limit in config. What version are you using?

**Comment by Tyrrrz** [comment]
There's no limit in config. What version are you using?

**Comment by axydavid** [comment]
it's the ;astest version, it's just that it resets back, which means the program doesn't support it.

**Comment by TheChiefMeat** [comment]
Having the exact same issue even with the configuration file set to read-only, the application resets the value each time.

**Comment by Tyrrrz** [comment]
I just tried editing the config, set my min temperature to 500k, my max to 8000k, both worked fine. Restarted LightBulb a few times and it also didn't overwrite the settings as long as I didn't touch the sliders.
