### ISSUE TITLE
My settings seem to disappear.

### ISSUE THREAD

**Issue by forkoz** [Tyrrrz/LightBulb#62]
I don't reboot my computer often... but when I do, it seems that all lightbulb settings get returned to defaults.

My config file is in AppData\Roaming\LightBulb, date created is Friday, ‎October ‎13, ‎2017, ‏‎6:16:37 PM. 
I had geo settings set there and updates off, etc. But now it is full of defaults, last modified on sunday when I rebooted the system.

I also notice lightbulb settings are only saved when the program quits. Maybe this has something to do with it. Happened twice before but I finally put 2 and 2 together.

**Comment by Tyrrrz** [comment]
Hmm, yeah it might not save settings correctly on shutdown under certain circumstances.

**Comment by forkoz** [comment]
Wish it didn't wipe out the settings I had in there. I should see what happens to a fresh install in a VM.

**Comment by Tyrrrz** [comment]
You can force it to save by manually closing LightBulb before shutting down. It doesn't wipe out the settings it just doesn't persist them.

Saving it to disk on every change is not an option because there are some settings that utilize sliders and those would trigger it very often. And saving it on exit clearly doesn't work sometimes during shutdown. One other option is to save it on a timer.

**Comment by forkoz** [comment]
Well I had settings saved and manually edited config file. I rebooted and I got default settings and default settings in the config file.

I can see what happens if I close LB before rebooting.

**Comment by Tyrrrz** [comment]
Oh I see. In that case it might be a completely different issue, perhaps the edits you made were invalid? Does it save without manually editing it?


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: forkoz <notifications@github.com> Date: 11/11/17  03:29  (GMT+02:00) To: Tyrrrz/LightBulb <LightBulb@noreply.github.com> Cc: Alexey Golub <tyrrrrrr@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [Tyrrrz/LightBulb] My settings seem to disappear. (#62) 
Well I had settings saved and manually edited config file. I rebooted and I got default settings and default settings in the config file.
I can see what happens if I close LB before rebooting.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Tyrrrz/LightBulb","title":"Tyrrrz/LightBulb","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Tyrrrz/LightBulb"}},"updates":{"snippets":[{"icon":"PERSON","message":"@forkoz in #62: Well I had settings saved and manually edited config file. I rebooted and I got default settings and default settings in the config file.\r\n\r\nI can see what happens if I close LB before rebooting."}],"action":{"name":"View Issue","url":"https://github.com/Tyrrrz/LightBulb/issues/62#issuecomment-343629180"}}}

**Comment by forkoz** [comment]
the edits were valid, it loaded and ran for a long time. The reboots were done by windows update when settings were lost. When I manually rebooted to try it the settings remained. I'll see what happens when I install the next patch.

What happens to the settings if the lightbulb process is killed? User above has the same OS... my work around now is having a copy of the .dat in case it happens again.

**Comment by Tyrrrz** [comment]
Hm. Does Windows reboot any differently when updating?
If the process is killed, the settings are just not saved, but they aren't reset. The settings are only reset if the configuration file is either deleted or somehow corrupt/invalid.

**Comment by Tyrrrz** [comment]
I think one possible scenario is that the system shuts down before LightBulb finishes writing settings to file, which I guess is quite likely if the drive it's writing to is in sleep mode or something like that.
I guess it can be solved by blocking Windows shutdown until settings are saved.

**Comment by Tyrrrz** [comment]
Ok it looks like the shutdown is delayed as is. Do you remember if LightBulb shows up on the "these programs are preventing Windows from shutting down" list?

**Comment by polyvertex** [comment]
Microsoft's recommendation on that matter is to write app's state when possible. You may delay the writing to the file off a few (milli)seconds when a change occurs in order to group and limit I/O accesses, but writing the config file only before shutdown/exit is a design mistake

**Comment by Tyrrrz** [comment]
@polyvertex you are right, this needs to be reworked.

**Comment by JJRcop** [comment]
I've found a workaround is to change your settings to how you like them, then right-click on the Configuration.dat file in Windows Explorer and check the Read Only option, this prevents LightBulb from writing to the file at all.
![image](https://user-images.githubusercontent.com/5211576/45846193-2d6e1a80-bcf5-11e8-8b9b-480d1a1f2de3.png)

**Comment by JJRcop** [comment]
I've found a workaround is to change your settings to how you like them, then right-click on the Configuration.dat file in Windows Explorer and check the Read Only option, this prevents LightBulb from writing to the file at all.
![image](https://user-images.githubusercontent.com/5211576/45846562-1976e880-bcf6-11e8-96bc-27bbe2ec3e64.png)
