### ISSUE TITLE
Behaviour after sleep/hibernation

### ISSUE THREAD

**Issue by bnbaz** [Tyrrrz/LightBulb#7]
When the computer enters sleep mode or hibernation while LightBulb has dimmed the colour temperature, it remains dimmed after waking up the computer at daytime. Toggling LightBulb off and on again helps.

Next time I encounter this issue I will check whether or not shortening the transition duration helps in seeing the right colour temperature sooner.

edit: this was with version 1.2, I think. Is there any way of checking the current LightBulb version?

**Comment by Tyrrrz** [comment]
> When the computer enters sleep mode or hibernation while LightBulb has dimmed the colour temperature, it remains dimmed after waking up the computer at daytime. 

Looks like the temperature was set to something low during the night, it got saved during hibernate and then, when recovered, the temperature stayed low during the day. The temperature updates (by default) in 1 minute intervals, so it would likely have set it back to normal after that time. Disabling/enabling also forces it to recalculate temperature.

I guess it's possible to "fix" this by reducing temperature update interval. I don't know if that's a good idea, because that will also mean it updates gamma a lot more often during transition (something I wanted to avoid, seeing how f.lux does it every 1 second).

There's another possible solution, which is to listen to [PowerModeChanged](https://msdn.microsoft.com/en-us/library/microsoft.win32.systemevents.powermodechanged.aspx) event, which sounds like it can be used to handle hibernation as well.

I'll try to implement a fix and comment back to you.

> Next time I encounter this issue I will check whether or not shortening the transition duration helps in seeing the right colour temperature sooner.

Shouldn't matter.

> edit: this was with version 1.2, I think. Is there any way of checking the current LightBulb version?

Not currently, I will implement it now.

**Comment by Tyrrrz** [comment]
I made some changes that should fix this issue and also added version info (shown in tooltip when hovering over "LightBulb" in main window). Can you compile this and test it?

**Comment by bnbaz** [comment]
I like your issue response speed :)

I'm afraid I can't help by building it, I have the ms build tools set up now but it's stuck on the dependencies now.

**Comment by Tyrrrz** [comment]
I built it for you [here](http://www.tyrrrz.me/dl/LightBulb_Install.zip)

**Comment by bnbaz** [comment]
Perfect thank you. I will make sure to replicate yesterday's actions and report back tomorrow morning (Europe).

**Comment by bnbaz** [comment]
Works!

**Comment by Tyrrrz** [comment]
Nice, thank you
