### ISSUE TITLE
No Option to set to auto start on login

### ISSUE THREAD

**Issue by JohnnyP78** [Tyrrrz/LightBulb#73]
It would be nice to have an option on the context menu so that LightBulb would start automatically when user logs in to windows.

**Comment by Tyrrrz** [comment]
It already sets itself to autostart when using the installer. What's the use case, do you want to be able to disable it or be able to enable it for portable version as well?

**Comment by JohnnyP78** [comment]
Hi Tyrrrz, it's exactly that :)

**Comment by mirh** [comment]
I don't remember the installer auto-enabling anything for me (but maybe it was because I installed it for the first time long time ago?)

Anyway, you can just put a shortcut to lightbulb into the start menu startup folder.

**Comment by JohnnyP78** [comment]
Yeah, sure or I can also go to regedit and place it on the following key:
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run]
The right question is:
Should the user have to do any of these? NO!

Usually programs like these simply have that option within it's own options.

**Comment by Tyrrrz** [comment]
That's reasonable and shouldn't be too hard to do

**Comment by JohnnyP78** [comment]
Thanks  Tyrrrz, just one additional note;
For this to work on portables the application has detect/know it's own location on the system, so that it adds the correct path on that reg key.

**Comment by sergeevabc** [comment]
Autostart should be handled by LightBulb itself, not its installer.

**Comment by sergeevabc** [comment]
By the way, v2 does not even run when unpacked to a Cyrillic folder, e.g. ```D:\Песочница\LightBulb2```.

**Comment by Tyrrrz** [comment]
@sergeevabc works for me

**Comment by sergeevabc** [comment]
@Tyrrrz, actually it does not run from any folder. I guess the reason is missing .Net Core 3 package. Well, since I have no intention to install another dependence (as it makes difficult to use on different machines), LightBulb is no longer for my cup of tea. Nevertheless consider adding some warning for users without that package (not the text warning in Releases section that is forgotten immediately after downloading, but the popup warning at the app’s startup).
