### ISSUE TITLE
Save/restore gamma settings when enabling/disabling

### ISSUE THREAD

**Issue by blamarche** [Tyrrrz/LightBulb#94]
I have my monitor color corrected via nvidia control panel color settings (contrast, brightness, gamma, vibrance and hue). When Lightbulb starts/stops or pauses it'd be great if it could restore these settings. As-is the user must open the nvidia control panel and re-apply the settings.

**Comment by Tyrrrz** [comment]
This is quite difficult mainly because LightBulb operates on a higher-level abstraction than just gamma. On the top level it uses color configuration which consists of temperature+brightness, which itself is an abstraction over color balance which is just a vector with color multiplier for each channel. So in order to properly tie in with custom gamma and have smooth enable/disable/transitions working with it, we would have to discard all of the levels of abstraction, which adds up complexity.

That said, the changes LightBulb makes are not on the hardware so you can instead calibrate your monitor directly and it shouldn't have conflicts with LightBulb, if that's an option.

**Comment by Tyrrrz** [comment]
Hey. It's quite weird that this happens. I tried changing gamma via AMD Radeon Settings and they seem to be separate from the gamma settings that LightBulb affects. I would expect Nvidia Control Panel to behave the same.

**Comment by blamarche** [comment]
Its alright, I thought it might be something like that. Thanks for checking it out (and for making lightbulb!)

**Comment by Tyrrrz** [comment]
Sorry for reviving an old issue @blamarche. Can you refresh my memory, does this problem still happen with latest version? I see above that I tried it myself and the gamma configuration was separate, does it not work the same way for you?

**Comment by blamarche** [comment]
Hi Tyrrrz, I don't even have a computer with the same configuration at this point. Since I'm the only report, I think its probably safe to close this 👍

**Comment by Tyrrrz** [comment]
Thanks!
